# Generated by Django 5.2.3 on 2025-06-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
            
),
        migrations.AddField(
             model_name='order',
             name='created_at',
             field=models.DateTimeField(auto_now_add=True),
             preserve_default=False,
),
]